app_news_api:
    type: rest
    prefix: /admin/api
    resource: Manuxi\SuluNewsBundle\Controller\Admin\NewsController
    name_prefix: sulu_news.
    options:
        expose: true
sulu_news_settings_api:
    type: rest
    prefix: /admin/api
    resource: Manuxi\SuluNewsBundle\Controller\Admin\SettingsController
    name_prefix: sulu_news.
    options:
        expose: true
