app_news_api:
    type: attribute
    resource: Manuxi\SuluNewsBundle\Controller\Admin\NewsController
    options:
        expose: true
sulu_news_settings_api:
    type: attribute
    resource: Manuxi\SuluNewsBundle\Controller\Admin\SettingsController
    options:
        expose: true
